### PR TITLE
feat: support Casbin Logger interface

### PR DESCRIPTION
**Pull request by basakest**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner @gaobinzhan plz review.

**Comment by leeqvip** [comment]
@basakest I found that `easyswoole` does not follow the `PSR-3` specification, so there is no need to use `psr3-bridge`, just implement `Casbin\Log\Logger` directly.

**Comment by leeqvip** [comment]
@basakest Please add `EasySwoole\Permission\Logger ` to config, and then set `logger` during initialization.

**Pull request merged**
