### PR TITLE
refactor: A code change that neither fixes a bug nor adds a feature.

### PR DESCRIPTION
**Pull request by Player626**

### CODE REVIEW

**Comment by Player626** [comment]
Some internal optimizations have been made.

**Comment by Player626** [comment]
Do not publish `release`,Because I don't understand, is there only one operation class, `Enforcer`?

**Comment by hsluoyz** [comment]
@techoner plz review.

**Comment by hsluoyz** [comment]
@basakest plz review.

**Comment by leeqvip** [comment]
@gaobinzhan Sorry for taking so long to respond, please modify commit messsge, refer to: https://github.com/semantic-release/semantic-release#commit-message-format , and merge multiple times into one commit

**Comment by hsluoyz** [comment]
@gaobinzhan

**Comment by Player626** [comment]
@techoner Haha, it doesn't matter. Now it's compressed into a submission.

**Comment by leeqvip** [comment]
@gaobinzhan It would be better to modify the commit message to "refactor: A code change that neither fixes a bug nor adds a feature"

**Comment by Player626** [comment]
@techoner Like this

**Comment by leeqvip** [comment]
> @techoner Like this

image
In this format, semantic-release will not trigger automatic release

**Comment by Player626** [comment]
How do I need to change it? You can write me a standard submission information directly.

**Comment by leeqvip** [comment]
> How do I need to change it? You can write me a standard submission information directly.

Like this: "refactor: A code change that neither fixes a bug nor adds a feature".
For details, please refer to: [Commit Message Format](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format).

**Comment by hsluoyz** [comment]
@gaobinzhan I think you can use git append to modify the message of this commit:

image

to something like: "feature: add xxx feature" or "fix: fix bug about xxx"

**Pull request merged**
